// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: api/notice.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoticeReaderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Msg   string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	// Types that are valid to be assigned to NoticeWay:
	//
	//	*NoticeReaderRequest_Email
	//	*NoticeReaderRequest_Phone
	NoticeWay     isNoticeReaderRequest_NoticeWay `protobuf_oneof:"notice_way"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeReaderRequest) Reset() {
	*x = NoticeReaderRequest{}
	mi := &file_api_notice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeReaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeReaderRequest) ProtoMessage() {}

func (x *NoticeReaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeReaderRequest.ProtoReflect.Descriptor instead.
func (*NoticeReaderRequest) Descriptor() ([]byte, []int) {
	return file_api_notice_proto_rawDescGZIP(), []int{0}
}

func (x *NoticeReaderRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *NoticeReaderRequest) GetNoticeWay() isNoticeReaderRequest_NoticeWay {
	if x != nil {
		return x.NoticeWay
	}
	return nil
}

func (x *NoticeReaderRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeReaderRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *NoticeReaderRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.NoticeWay.(*NoticeReaderRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

type isNoticeReaderRequest_NoticeWay interface {
	isNoticeReaderRequest_NoticeWay()
}

type NoticeReaderRequest_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type NoticeReaderRequest_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

func (*NoticeReaderRequest_Email) isNoticeReaderRequest_NoticeWay() {}

func (*NoticeReaderRequest_Phone) isNoticeReaderRequest_NoticeWay() {}

type Book struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Title  string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// int64 price = 3;
	// google.protobuf.Int64Value price = 3;
	Price         *int64                  `protobuf:"varint,3,opt,name=price,proto3,oneof" json:"price,omitempty"`
	SalePrice     *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=sale_price,json=salePrice,proto3" json:"sale_price,omitempty"` // float64
	Memo          *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	Info          *Book_Info              `protobuf:"bytes,6,opt,name=info,proto3" json:"info,omitempty"` // 嵌套
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_api_notice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_api_notice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_api_notice_proto_rawDescGZIP(), []int{1}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPrice() int64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *Book) GetSalePrice() *wrapperspb.DoubleValue {
	if x != nil {
		return x.SalePrice
	}
	return nil
}

func (x *Book) GetMemo() *wrapperspb.StringValue {
	if x != nil {
		return x.Memo
	}
	return nil
}

func (x *Book) GetInfo() *Book_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

type UpdateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 操作人
	Op string `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	// 要更新的书籍信息
	Book *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	// 要更新的字段
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_api_notice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_notice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_api_notice_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBookRequest) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *UpdateBookRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type Book_Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"` // book.info.b
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book_Info) Reset() {
	*x = Book_Info{}
	mi := &file_api_notice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book_Info) ProtoMessage() {}

func (x *Book_Info) ProtoReflect() protoreflect.Message {
	mi := &file_api_notice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book_Info.ProtoReflect.Descriptor instead.
func (*Book_Info) Descriptor() ([]byte, []int) {
	return file_api_notice_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Book_Info) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *Book_Info) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

var File_api_notice_proto protoreflect.FileDescriptor

const file_api_notice_proto_rawDesc = "" +
	"\n" +
	"\x10api/notice.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a google/protobuf/field_mask.proto\"e\n" +
	"\x13NoticeReaderRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x16\n" +
	"\x05email\x18\x02 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x03 \x01(\tH\x00R\x05phoneB\f\n" +
	"\n" +
	"notice_way\"\x8c\x02\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x19\n" +
	"\x05price\x18\x03 \x01(\x03H\x00R\x05price\x88\x01\x01\x12;\n" +
	"\n" +
	"sale_price\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\tsalePrice\x120\n" +
	"\x04memo\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x04memo\x12\x1e\n" +
	"\x04info\x18\x06 \x01(\v2\n" +
	".Book.InfoR\x04info\x1a\"\n" +
	"\x04Info\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01bB\b\n" +
	"\x06_price\"{\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x19\n" +
	"\x04book\x18\x02 \x01(\v2\x05.BookR\x04book\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\x13Z\x11protobuf_demo/apib\x06proto3"

var (
	file_api_notice_proto_rawDescOnce sync.Once
	file_api_notice_proto_rawDescData []byte
)

func file_api_notice_proto_rawDescGZIP() []byte {
	file_api_notice_proto_rawDescOnce.Do(func() {
		file_api_notice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_notice_proto_rawDesc), len(file_api_notice_proto_rawDesc)))
	})
	return file_api_notice_proto_rawDescData
}

var file_api_notice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_notice_proto_goTypes = []any{
	(*NoticeReaderRequest)(nil),    // 0: NoticeReaderRequest
	(*Book)(nil),                   // 1: Book
	(*UpdateBookRequest)(nil),      // 2: UpdateBookRequest
	(*Book_Info)(nil),              // 3: Book.Info
	(*wrapperspb.DoubleValue)(nil), // 4: google.protobuf.DoubleValue
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
	(*fieldmaskpb.FieldMask)(nil),  // 6: google.protobuf.FieldMask
}
var file_api_notice_proto_depIdxs = []int32{
	4, // 0: Book.sale_price:type_name -> google.protobuf.DoubleValue
	5, // 1: Book.memo:type_name -> google.protobuf.StringValue
	3, // 2: Book.info:type_name -> Book.Info
	1, // 3: UpdateBookRequest.book:type_name -> Book
	6, // 4: UpdateBookRequest.update_mask:type_name -> google.protobuf.FieldMask
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_notice_proto_init() }
func file_api_notice_proto_init() {
	if File_api_notice_proto != nil {
		return
	}
	file_api_notice_proto_msgTypes[0].OneofWrappers = []any{
		(*NoticeReaderRequest_Email)(nil),
		(*NoticeReaderRequest_Phone)(nil),
	}
	file_api_notice_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_notice_proto_rawDesc), len(file_api_notice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_notice_proto_goTypes,
		DependencyIndexes: file_api_notice_proto_depIdxs,
		MessageInfos:      file_api_notice_proto_msgTypes,
	}.Build()
	File_api_notice_proto = out.File
	file_api_notice_proto_goTypes = nil
	file_api_notice_proto_depIdxs = nil
}
